def pop
  [
    'Adam Lambert',
    'Adele',
    'Alessia Cara',
    'Alex & Sierra',
    'Aloe Blacc',
    'Andy Grammer',
    'Ariana Grande',
    'Avery Wilson',
    'Bea Miller',
    'Becky G',
    'Beyoncé',
    'Black Eyed Peas',
    'Blue Swede',
    'Britney Spears',
    'Bruno Mars',
    'Calvin Harris',
    'Carly Rae Jepsen',
    'Céline Dion',
    'Charli XCX',
    'Charlie Puth',
    'Christina Aguilera',
    'Christina Perri',
    'Ciara',
    'Clean Bandit',
    'Colbie Caillat',
    'Daft Punk',
    'Daniel Skye',
    'Disclosure',
    'Don McLean',
    'Ella Henderson',
    'Ellie Goulding',
    'Emeli Sandé',
    'Enrique Iglesias',
    'Fifth Harmony',
    'Florence + The Machine',
    'Florida Georgia Line',
    'Gorgon City',
    'A Great Big World',
    'Green Day',
    'Hot Chocolate',
    'Imogen Heap',
    'Jacquie Lee',
    'Jake Miller',
    'Jason Derulo',
    'Jason Mraz',
    'Jennifer Lopez',
    'Jess Glynne',
    'Jessie J',
    'Jessie Ware',
    'John Lennon',
    'Josh Groban',
    'Justin Timberlake',
    'Katy B',
    'Katy Perry',
    'Katy Tiz',
    'Kelly Clarkson',
    'Kesington Kross',
    'Ke$ha',
    'Lady Gaga',
    'LunchMoney Lewis',
    'Madonna',
    'MAGIC!',
    'Mariah Carey',
    'Marina and The Diamonds',
    'Mark Ronson',
    'Marlon Roudette',
    'Maroon 5',
    'Meghan Trainor',
    'Michael Jackson',
    'Miley Cyrus',
    'MKTO',
    'MNEK',
    'Natalie La Rose',
    'Natasha Bedingfield',
    'Nick Jonas',
    'Nico & Vinz',
    'Oily Murs',
    'One Direction',
    'OneRepublic',
    'P!NK',
    'Pharrell Williams',
    'Phillip Phillips',
    'Pia Mia',
    'Pitbull',
    'Prince Royce',
    'Pussycat Dolls',
    'R5',
    'Rachel Platten',
    'Rihanna',
    'Rio Flare',
    'Robin Schulz',
    'Robin Thicke',
    'Sabrina Carpenter',
    'Sam Smith',
    'Sara Bareilles',
    'The Script',
    'Selena Gomez',
    'Shakira',
    'Shawn Mendes',
    'Sheppard',
    'Sia',
    'SNBRN',
    'Sofia Karlberg',
    'Tori Kelly',
    'V V Brown',
    'Walk The Moon',
    'Whitney Houston',
    'Who Is Fancy'
]
end