def rb
  [
    'Adrian Marcel',
    'Akon',
    'Al Green',
    'Alicia Keys',
    'Amy Winehouse',
    'Anthony Hamilton',
    'Anthony Lewis',
    'Aretha Franklin',
    'Ashanti',
    'August Alsina',
    'Baby Bash',
    'Bell Biv DeVoe',
    'Ben E. King',
    'Bill Withers',
    'Billy Miles',
    'Blackbear',
    'Boyz II Men',
    'Chaka Khan',
    'Chris Brown',
    'Christina Aguilera',
    'Ciara',
    'The Commodores',
    'Cupid',
    "Destiny's Child",
    'Dobie Gray',
    'The Drifters',
    'Earth, Wind & Fire',
    'En Vogue',
    'Estelle',
    'Fetty Wap',
    'The Five Stairsteps',
    'The Foundations',
    'Ginuwine',
    'India Carney',
    'The Intruders',
    'Jackson 5',
    'Jamie Foxx',
    'Janelle Monáe',
    'Jazmine Sullivan',
    'Jeremih',
    'Jess Glynne',
    'Jhené Aiko',
    'Jidenna',
    'Jill Scott',
    'Jodeci',
    'John Legend',
    'K. Michelle',
    'Kehlani',
    'Kelly Rowland',
    'Kenny Littimore',
    'Keri Hilson',
    'Kool & The Gang',
    'Lauryn Hill',
    'Leela James',
    'Leon Bridges',
    'Lionel Richie',
    'Lulu James',
    'Luther Vandross',
    'Mariah Carey',
    'Mario',
    'Marvin Gaye',
    'Mary J. Blige',
    'Maxwell',
    'Miguel',
    'Mila J',
    'Montell Jordan',
    'Ne-Yo',
    'Nick Jonas',
    'Nikka Costa',
    'Omarion',
    'Otis Redding',
    'PARTYNEXTDOOR',
    'Percy Sledge',
    'Pia Mia',
    'Prince',
    'R. Kelly',
    'Rico Love',
    'Roberta Flack',
    'Robin S.',
    'Sade',
    'Sam Cooke',
    'Sevyn Street',
    'SoMo',
    'Stevie Wonder',
    'Taio Cruz',
    'Tamar Braxton',
    'Tinashe',
    'Tink',
    'TLC',
    'Trey Songz',
    'Tyrese',
    'Usher',
    'The Weeknd',
    'Whitney Houston'
  ]
end