module SongsHelper

  def genre_artists
    [

      {
        :genre => "country",
        :artists => [
          'Little Big Town',
          'Blake Shelton',
          'Sam Hunt',
          'Zac Brown Band',
          'Eric Church',
          'Florida Georgia Line',
          'A Thousand Horses',
          'Billy Currington',
          'Tyler Farr',
          'Canaan Smith',
          'Jason Aldean',
          'Kelsea Ballerini',
          'Thomas Rhett',
          'Lee Brice',
          'Carrie Underwood',
          'Luke Bryan',
          'Keith Urban',
          'Dierks Bentley',
          'Chris Janson',
          'Eric Paslay',
          'Brantley Gilbert',
          'Kenny Chesney',
          'Easton Corbin',
          'Cole Swindell',
          'Miranda Lambert',
          'Michael Ray',
          'Alan Jackson',
          'Ashley Monroe',
          'The Band Perry',
          'Brad Paisley',
          'Brett Eldredge',
          'Brothers Osborne',
          'The Charlie Daniels Band',
          'Chase Rice',
          'Chris Young',
          'Dan + Shay',
          'Darius Rucker',
          'Dustin Lynch',
          'Eli Young Band',
          'George Strait',
          'Granger Smith',
          'Jana Kramer',
          'Johnny Cash',
          'Josh Turner',
          'Kacey Musgraves',
          'Kip Moore',
          'Lady Antebellum',
          'Lauren Alaina',
          'Lee Ann Womack',
          'Martina McBride',
          'RaeLynn',
          'Randy Houser',
          'Rascal Flatts',
          'Reba McEntire',
          'Tim McGraw',
          'Trace Adkins',
          'Tyler Farr',
          'Dixie Chicks',
          'Shania Twain',
          'LeAnn Rimes',
          'Trisha Yearwood',
          'Sammy Kershaw',
          'Billy Ray Cyrus',
          'Faith Hill',
          'Vince Gill',
          'Brooks & Dunn',
          'Lonestar',
          'Randy Travis',
          'Dolly Parton',
          'Mary Chapin Carpenter',
          'Glen Campbell',
          'Patsy Cline',
          'Waylon Jennings',
          'Nitty Gritty Dirt Band',
          'Willie Nelson',
          'The Judds',
          'Alabama',
          'Merle Haggard',
          'John Michael Montgomery',
          'Emmylou Harris',
          'Steve Earle',
          'Hank Williams Jr.',
          'Loretta Lynn',
          'Kenny Rogers',
          'Gram Parsons',
          'Gretchen Wilson',
          'Lyle Lovett',
          'Hank Williams',
          'Buck Owens',
          'Mark Chesnutt',
          'Laura Bell Bundy',
          'Gary Allan',
          'The Mavericks',
          'Tracy Byrd',
          'Jewel',
          'Jimmy Wayne',
          'Montgomery Gentry',
          'Tanya Tucker',
          'Scotty McCreery',
          'Rhett Akins'
        ]
      }
    ]
  end

end
