module SongsHelper

  def genre_artists
    [
      # alternative rock
      {
        :genre => "alternative rock",
        :artists => [
          'Alabama Shakes',
          'All Time Low',
          'The All American Rejects',
          'alt-J',
          'American Authors',
          'Andrew McMahon in the Wilderness',
          'Arctic Monkeys',
          'AWOLNATION',
          'Band of Horses',
          'Banks',
          'Bastille',
          'Best Coast',
          'Big Data',
          'Birdy',
          'The Black Keys',
          'Bleachers',
          'Brandon Flowers',
          'Bring Me the Horizon',
          'Cage the Elephant',
          'Capital Cities',
          'Cold War Kids',
          'Coldplay',
          'Death Cab for Cutie',
          'Echosmith',
          'Edward Sharpe & The Magnetic Zeros',
          'Elle King',
          'Evanescence',
          'Fall Out Boy',
          'Family of the Year',
          'Florence + The Machine',
          'Foster the People',
          'Fun.',
          'Glass Animals',
          'Gorillaz',
          'Gotye',
          'The Head and the Heart',
          'Houndmouth',
          'Hozier',
          'In The Valley Below',
          'James Bay',
          'Jeff Buckley',
          'Jimmy Eat World',
          'The Killers',
          'Kodaline',
          'KONGOS',
          'Lana Del Rey',
          'LINKIN PARK',
          'Lord Huron',
          'Lorde',
          'The Lumineers',
          'M.I.A.',
          'Madisen Ward and the Mama Bear',
          'Meg Myers',
          'Melanie Martinez',
          'Michael Franti & Spearhead',
          'Milky Chance',
          'MisterWives',
          'Modest Mouse',
          'The Moth & The Flame',
          'The Mowglis',
          'Mumford & Sons',
          'Muse',
          'My Chemical Romance',
          'My Morning Jacket',
          'Nate Ruess',
          'The Neighbourhood',
          'Neon Trees',
          'Nirvana',
          'Oasis',
          'Of Monsters and Men',
          'The Offspring',
          'Panic! At the Disco',
          'Paramore',
          'Red Hot Chili Peppers',
          'Sublime',
          'Third Eye Blind',
          'Tove Lo',
          'twenty one pilots',
          'Vance Joy',
          'WALK THE MOON',
          'Weezer',
          'The White Stripes',
          'X Ambassadors',
          'The xx',
          'Young Rising Sons',
          'The 1975',
          'Pvris',
          'Halsey',
          'Audioslave',
          'blink-182',
          'Bon Iver',
          'Boys Like Girls',
          'Broods',
          'Tegan and Sara',
          'Bad Suns',
          'City and Colour',
          'ZZ Ward',
          'Sum 41',
          'The Civil Wars',
          'Green Day'
        ]
      },

      # blues
      {
        :genre => "blues",
        :artists => [
          'Aaron Neville',
          'Albert King',
          'B.B. King',
          'Band of Oz',
          'Barbara Smith',
          'Bessie Smith',
          'Beth Hart',
          'Big Mama Thornton',
          'Bill Doggett',
          'Blind Willie Johnson',
          'The Blues Brothers',
          'Blues Image',
          'Blues Saraceno',
          'Bo Diddley',
          'Bobby Bland',
          'Brother Bones & His Shadows',
          'Buddy Guy',
          'Canned Heat',
          'Catalinas',
          'Chuck Berry',
          'Clarence Carter',
          'Climax Blues Band',
          'Delbert McClinton',
          'Dorothy Moore',
          'Elmore James',
          'Elvin Bishop',
          'The Embers',
          'Eric Bibb',
          'Eric Clapton',
          'Etta James',
          'Frankie Ford',
          'Freddie King',
          'Gary Moore',
          'Geraldine Hunt',
          'Gregg Allman',
          'Howlin Wolf',
          'Jwonn',
          'Jimmy Reed',
          'Joe Bonamassa',
          'John Lee Hooker',
          'Johnnie Taylor',
          'Jonny Lang',
          'Keb Mo',
          'Kenny Wayne Shepherd',
          'King Floyd',
          'Koko Taylor',
          'Latimore',
          'Leadbelly',
          'Lebrado',
          'Little Walter',
          'The Louisiana Blues Brothas',
          'Meghan Linsey',
          'Mel Waiters',
          'Mia Z',
          'Michael Combs',
          'Muddy Waters',
          'Nellie Tiger Travis',
          'Nina Simone',
          'Otis Redding',
          'Otis Taylor',
          'Peter Green',
          'Pokey',
          'R.L. Burnside',
          'Ray Bonneville',
          'Ray Charles',
          'Ringo Starr',
          'Robert Cray',
          'Robert Johnson',
          'Ruby Friedman Orchestra',
          'Sena Ehrhardt',
          'Slim Harpo',
          'Son House',
          'Susan Tedeschi',
          'Swingin Medallions',
          'T-Bone Walker',
          'T.k. Soul',
          'Tab Benoit',
          'Tedeschi Trucks Band',
          'Them',
          'Theodis Ealey',
          'Tommy G And Stormy Weather',
          'Willie Dixon',
          'The Wood Brothers',
          'Z.Z. Hill',
          'Stevie Ray Vaughan',
          'ZZ Top',
          'Johnny Winter',
          'Lonnie Mack',
          'Lightnin Hopkins',
          'Bonnie Raitt',
          'Otis Spann',
          'Magic Sam',
          'Jimmy Reed',
          'Albert Collins',
          'Guitar Shorty',
          'Seasick Steve',
          'Mance Lipscomb'
        ]
      },

      # classical
      {
        :genre => "classical",
        :artists => [
          "Ludwig van Beethoven",
          "Wolfgang Amadeus Mozart",
          "Johann Sebastian Bach",
          "Richard Wagner",
          "Joseph Haydn",
          "Johannes Brahms",
          "Franz Schubert",
          "Peter Ilyich Tchaikovsky",
          "George Frideric Handel",
          "Igor Stravinsky",
          "Robert Schumann",
          "Frederic Chopin",
          "Felix Mendelssohn",
          "Claude Debussy",
          "Franz Liszt",
          "Antonin Dvorak",
          "Giuseppe Verdi",
          "Gustav Mahler",
          "Hector Berlioz",
          "Antonio Vivaldi",
          "Richard Strauss",
          "Sergei Prokofiev",
          "Dmitri Shostakovich",
          "Béla Bartók",
          "Anton Bruckner",
          "Giovanni Pierluigi da Palestrina",
          "Claudio Monteverdi",
          "Jean Sibelius",
          "Maurice Ravel",
          "Ralph Vaughan Williams",
          "Modest Mussorgsky",
          "Giacomo Puccini",
          "Henry Purcell",
          "Gioachino Rossini",
          "Edward Elgar",
          "Sergei Rachmaninoff",
          "Camille Saint-Saëns",
          "Josquin Des Prez -",
          "Nikolai Rimsky-Korsakov",
          "Carl Maria von Weber",
          "Jean-Philippe Rameau",
          "Jean-Baptiste Lully",
          "Gabriel Fauré",
          "Edvard Grieg",
          "Christoph Willibald Gluck",
          "Arnold Schoenberg",
          "Charles Ives",
          "Paul Hindemith",
          "Olivier Messiaen",
          "Aaron Copland"
        ]
      },

      # country
      {
        :genre => "country",
        :artists => [
          'Little Big Town',
          'Blake Shelton',
          'Sam Hunt',
          'Zac Brown Band',
          'Eric Church',
          'Florida Georgia Line',
          'A Thousand Horses',
          'Billy Currington',
          'Tyler Farr',
          'Canaan Smith',
          'Jason Aldean',
          'Kelsea Ballerini',
          'Thomas Rhett',
          'Lee Brice',
          'Carrie Underwood',
          'Luke Bryan',
          'Keith Urban',
          'Dierks Bentley',
          'Chris Janson',
          'Eric Paslay',
          'Brantley Gilbert',
          'Kenny Chesney',
          'Easton Corbin',
          'Cole Swindell',
          'Miranda Lambert',
          'Michael Ray',
          'Alan Jackson',
          'Ashley Monroe',
          'The Band Perry',
          'Brad Paisley',
          'Brett Eldredge',
          'Brothers Osborne',
          'The Charlie Daniels Band',
          'Chase Rice',
          'Chris Young',
          'Dan + Shay',
          'Darius Rucker',
          'Dustin Lynch',
          'Eli Young Band',
          'George Strait',
          'Granger Smith',
          'Jana Kramer',
          'Johnny Cash',
          'Josh Turner',
          'Kacey Musgraves',
          'Kip Moore',
          'Lady Antebellum',
          'Lauren Alaina',
          'Lee Ann Womack',
          'Martina McBride',
          'RaeLynn',
          'Randy Houser',
          'Rascal Flatts',
          'Reba McEntire',
          'Tim McGraw',
          'Trace Adkins',
          'Tyler Farr',
          'Dixie Chicks',
          'Shania Twain',
          'LeAnn Rimes',
          'Trisha Yearwood',
          'Sammy Kershaw',
          'Billy Ray Cyrus',
          'Faith Hill',
          'Vince Gill',
          'Brooks & Dunn',
          'Lonestar',
          'Randy Travis',
          'Dolly Parton',
          'Mary Chapin Carpenter',
          'Glen Campbell',
          'Patsy Cline',
          'Waylon Jennings',
          'Nitty Gritty Dirt Band',
          'Willie Nelson',
          'The Judds',
          'Alabama',
          'Merle Haggard',
          'John Michael Montgomery',
          'Emmylou Harris',
          'Steve Earle',
          'Hank Williams Jr.',
          'Loretta Lynn',
          'Kenny Rogers',
          'Gram Parsons',
          'Gretchen Wilson',
          'Lyle Lovett',
          'Hank Williams',
          'Buck Owens',
          'Mark Chesnutt',
          'Laura Bell Bundy',
          'Gary Allan',
          'The Mavericks',
          'Tracy Byrd',
          'Jewel',
          'Jimmy Wayne',
          'Montgomery Gentry',
          'Tanya Tucker',
          'Scotty McCreery',
          'Rhett Akins'
        ]
      },

      # hip hop
      {
        :genre => "hip hop",
        :artists => [
          "Run-DMC",
          "Public Enemy",
          "2Pac",
          "Jay-Z",
          "OutKast",
          "N.W.A",
          "Notorious B.I.G",
          "A Tribe Called Quest",
          "Nas",
          "Ice Cube",
          "LL Cool J",
          "Kanye West",
          "Scarface",
          "Wu-Tang Clan",
          "Dr. Dre",
          "Eminem",
          "UGK",
          "Beastie Boys",
          "Slick Rick",
          "Snoop Dogg",
          "The Roots",
          "E-40",
          "Common",
          "Ghostface Killah",
          "Mos Def",
          "Salt-N-Pepa",
          "Busta Rhymes",
          "DJ Jazzy Jeff & the Fresh Prince",
          "T.I.",
          "Queen Latifah",
          "Raekwon",
          "Cold Crush Brothers",
          "Redman",
          "Eazy-E",
          "Talib Kweli",
          "Lil Kim",
          "Ludacris",
          "Cypress Hill",
          "DMX",
          "Mobb Deep",
          "Digable Planets",
          "The Pharcyde",
          "Missy Elliott",
          "Ice-T",
          "Lupe Fiasco",
          "Brand Nubian",
          "Ras Kass",
          "Arrested Development",
          "50 Cent",
          "Eve",
          "The Sugarhill Gang",
          "Method Man",
          "Jeezy",
          "Da Brat",
          "Big Punisher",
          "The D.O.C.",
          "X-Clan",
          "Diddy",
          "Mystikal",
          "Foxy Brown",
          "Wiz Khalifa",
          "Drake",
          "Tyga",
          "Chris Brown",
          "Kid Ink",
          "Meek Mill",
          "Rick Ross",
          "Big Sean",
          "Nicki Minaj",
          "Mac Miller",
          "Juicy J",
          "Kendrick Lamar",
          "2 Chainz",
          "ASAP Rocky",
          "Chief Keef",
          "Future",
          "DJ Khaled",
          "Kid Cudi",
          "Frank Ocean",
          "Pusha T",
          "B.o.B",
          "T-Pain",
          "Lloyd Banks",
          "Machine Gun Kelly",
          "Usher",
          "Migos",
          "Jim Jones",
          "Yelawolf",
          "Tech N9ne",
          "Ne-Yo",
          "Cassidy",
          "Joey Bada$$",
          "Birdman",
          "G-Unit",
          "Nelly",
          "Fat Joe",
          "Tyler, The Creator",
          "Chamillionaire",
          "Slaughterhouse",
          "Run the Jewels"
        ]
      },

      # jazz
      {
        :genre => "jazz",
        :artists => [
          "Louis Armstrong",
          "Duke Ellington",
          "Miles Davis",
          "Charlie Parker",
          "John Coltrane",
          "Dizzy Gillespie",
          "Billie Holiday",
          "Thelonious Monk",
          "Charles Mingus",
          "Count Basie",
          "Lester Young",
          "Ella Fitzgerald",
          "Coleman Hawkins",
          "Sonny Rollins",
          "Sidney Bechet",
          "Art Blakey & The Jazz Messengers",
          "Ornette Coleman",
          "Bill Evans",
          "Art Tatum",
          "Benny Goodman",
          "Clifford Brown",
          "Stan Getz",
          "Jelly Roll Morton",
          "Jimmy Rowles",
          "Herbie Hancock",
          "Bud Powell",
          "Wayne Shorter",
          "Fletcher Henderson",
          "Django Reinhardt",
          "Horace Silver",
          "Dave Brubeck",
          "Rahsaan Roland Kirk",
          "Cecil Taylor",
          "King Oliver",
          "Sun Ra",
          "Gil Evans",
          "Lionel Hampton",
          "Art Pepper",
          "Eric Dolphy",
          "Oscar Peterson",
          "Charlie Christian",
          "Ben Webster",
          "Fats Waller",
          "Earl Hines",
          "Woody Herman",
          "Wes Montgomery",
          "J.J. Johnson",
          "John McLaughlin",
          "Artie Shaw",
          "Lee Morgan",
          "Chick Corea",
          "The Modern Jazz Quartet",
          "Max Roach",
          "Anthony Braxton",
          "Bix Beiderbecke",
          "Cannonball Adderley",
          "Dexter Gordon",
          "Keith Jarrett",
          "Lee Konitz",
          "Stan Kenton",
          "Chet Baker",
          "Roy Eldridge",
          "Joe Henderson",
          "McCoy Tyner",
          "Gerry Mulligan",
          "Benny Carter",
          "Teddy Wilson",
          "Lennie Tristano",
          "Freddie Hubbard",
          "Jimmy Smith",
          "Mary Lou Williams",
          "George Russell",
          "Fats Navarro",
          "Albert Ayler",
          "Bennie Moten",
          "Jimmie Lunceford",
          "Wynton Marsalis",
          "Charlie Haden",
          "Erroll Garner",
          "Billy Strayhorn",
          "Meade 'Lux' Lewis",
          "Jack Teagarden",
          "Johnny Hodges",
          "Chick Webb",
          "Jimmy Giuffre",
          "Jaco Pastorius",
          "Hank Mobley",
          "Elvin Jones",
          "Evan Parker",
          "Paul Chambers",
          "Ron Carter",
          "Philly Joe Jones",
          "Carla Bley",
          "Curtis Fuller",
          "James Carter",
          "Donald Byrd",
          "Johnny Dodds",
          "Glenn Miller"
        ]
      },

      # pop
      {
        :genre => "pop",
        :artists => [
          'Adam Lambert',
          'Adele',
          'Alessia Cara',
          'Alex & Sierra',
          'Aloe Blacc',
          'Andy Grammer',
          'Ariana Grande',
          'Avery Wilson',
          'Bea Miller',
          'Becky G',
          'Beyoncé',
          'Black Eyed Peas',
          'Blue Swede',
          'Britney Spears',
          'Bruno Mars',
          'Calvin Harris',
          'Carly Rae Jepsen',
          'Céline Dion',
          'Charli XCX',
          'Charlie Puth',
          'Christina Aguilera',
          'Christina Perri',
          'Ciara',
          'Clean Bandit',
          'Colbie Caillat',
          'Daft Punk',
          'Daniel Skye',
          'Disclosure',
          'Don McLean',
          'Ella Henderson',
          'Ellie Goulding',
          'Emeli Sandé',
          'Enrique Iglesias',
          'Fifth Harmony',
          'Florence + The Machine',
          'Florida Georgia Line',
          'Gorgon City',
          'A Great Big World',
          'Green Day',
          'Hot Chocolate',
          'Imogen Heap',
          'Jacquie Lee',
          'Jake Miller',
          'Jason Derulo',
          'Jason Mraz',
          'Jennifer Lopez',
          'Jess Glynne',
          'Jessie J',
          'Jessie Ware',
          'John Lennon',
          'Josh Groban',
          'Justin Timberlake',
          'Katy B',
          'Katy Perry',
          'Katy Tiz',
          'Kelly Clarkson',
          'Kesington Kross',
          'Ke$ha',
          'Lady Gaga',
          'LunchMoney Lewis',
          'Madonna',
          'MAGIC!',
          'Mariah Carey',
          'Marina and The Diamonds',
          'Mark Ronson',
          'Marlon Roudette',
          'Maroon 5',
          'Meghan Trainor',
          'Michael Jackson',
          'Miley Cyrus',
          'MKTO',
          'MNEK',
          'Natalie La Rose',
          'Natasha Bedingfield',
          'Nick Jonas',
          'Nico & Vinz',
          'One Direction',
          'OneRepublic',
          'P!NK',
          'Pharrell Williams',
          'Phillip Phillips',
          'Pia Mia',
          'Pitbull',
          'Prince Royce',
          'Pussycat Dolls',
          'R5',
          'Rachel Platten',
          'Rihanna',
          'Robin Schulz',
          'Robin Thicke',
          'Sabrina Carpenter',
          'Sam Smith',
          'Sara Bareilles',
          'The Script',
          'Selena Gomez',
          'Shakira',
          'Shawn Mendes',
          'Sheppard',
          'Sia',
          'SNBRN',
          'Sofia Karlberg',
          'Tori Kelly',
          'V V Brown',
          'Walk The Moon',
          'Whitney Houston',
          'Who Is Fancy'
        ]
      },

      # r&b
      {
        :genre => "r&b",
        :artists => [
          'Adrian Marcel',
          'Akon',
          'Al Green',
          'Alicia Keys',
          'Amy Winehouse',
          'Anthony Hamilton',
          'Anthony Lewis',
          'Aretha Franklin',
          'Ashanti',
          'August Alsina',
          'Baby Bash',
          'Bell Biv DeVoe',
          'Ben E. King',
          'Bill Withers',
          'Billy Miles',
          'Blackbear',
          'Boyz II Men',
          'Chaka Khan',
          'Chris Brown',
          'Christina Aguilera',
          'Ciara',
          'The Commodores',
          'Cupid',
          "Destiny's Child",
          'Dobie Gray',
          'The Drifters',
          'Earth, Wind & Fire',
          'En Vogue',
          'Estelle',
          'Fetty Wap',
          'The Five Stairsteps',
          'The Foundations',
          'Ginuwine',
          'The Intruders',
          'Jackson 5',
          'Jamie Foxx',
          'Janelle Monáe',
          'Jazmine Sullivan',
          'Jeremih',
          'Jess Glynne',
          'Jhené Aiko',
          'Jidenna',
          'Jill Scott',
          'Jodeci',
          'John Legend',
          'K. Michelle',
          'Kehlani',
          'Kelly Rowland',
          'Kenny Lattimore',
          'Keri Hilson',
          'Kool & The Gang',
          'Lauryn Hill',
          'Leela James',
          'Leon Bridges',
          'Lionel Richie',
          'Lulu James',
          'Luther Vandross',
          'Mariah Carey',
          'Mario',
          'Marvin Gaye',
          'Mary J. Blige',
          'Maxwell',
          'Miguel',
          'Mila J',
          'Montell Jordan',
          'Ne-Yo',
          'Nick Jonas',
          'Nikka Costa',
          'Omarion',
          'Otis Redding',
          'PARTYNEXTDOOR',
          'Percy Sledge',
          'Pia Mia',
          'Prince',
          'R. Kelly',
          'Rico Love',
          'Roberta Flack',
          'Robin S.',
          'Sade',
          'Sam Cooke',
          'Sevyn Streeter',
          'SoMo',
          'Stevie Wonder',
          'Taio Cruz',
          'Tamar Braxton',
          'Tinashe',
          'Tink',
          'TLC',
          'Trey Songz',
          'Tyrese',
          'Usher',
          'The Weeknd',
          'Whitney Houston'
        ]
      },

      # singer/songwriter
      {
        :genre => "singer/songwriter",
        :artists => [
          'Agnes Obel',
          'Alexander Cardinale',
          'Ali Brustofski',
          'Amos Lee',
          'Angus & Julia Stone',
          'Arlo Guthrie',
          'Aron Wright',
          'Ben Howard',
          'Ben Rector',
          'Bob Dylan',
          'Boyce Avenue',
          'Brandi Carlile',
          'Daisy May',
          'Damien Rice',
          'Daniela Andrade',
          'David Gray',
          'Distant Cousins',
          'Drew Holcomb & The Neighbors',
          'Ed Sheeran',
          'Erin McCarley',
          'Gabrielle Aplin',
          'Gavin James',
          'George Ezra',
          'Gordon Lightfoot',
          'Grant Terry',
          'Greg Holden',
          'Greg Laswell',
          'Gregory Alan Isakov',
          'Hozier',
          'Indigo Girls',
          'Ivan & Alyosha',
          'Jacob Whitesides',
          'James Taylor',
          'Jasmine Thompson',
          'Jason Isbell',
          'Jessica Mears',
          'John Prine',
          'Iris DeMent',
          'Joni Mitchell',
          'Josh Garrels',
          'Joshua Radin',
          'Judy Collins',
          'Landon Austin',
          'Lauren OConnell',
          'Lennon & Maisy',
          'Leonard Cohen',
          'Louisa Wendorff',
          'Lucy Rose',
          'Madilyn Bailey',
          'Mary Lambert',
          'Matt Nathanson',
          'Nahko and Medicine for the People',
          'Neil Young & Crazy Horse',
          'Noah Gundersen',
          'Noel Paul Stookey',
          'Nolan Wilson',
          'Norah Jones',
          'The Oh Hellos',
          'Old Crow Medicine Show',
          'The Paper Kites',
          'Passenger',
          'Peter Bradley Adams',
          'Peter, Paul & Mary',
          'Rhett Miller',
          'Rhiannon Giddens',
          'Iron & Wine',
          'Rosi Golan',
          'Ruth B.',
          'Ryan Adams',
          'Saint Raymond',
          'Sheryl Crow',
          'Simon & Garfunkel',
          'Sleeping At Last',
          'Spencer Combs',
          'Sufjan Stevens',
          'Tatiana Manaois',
          'Tom Odell',
          'Tracy Chapman',
          'Tyler Ward',
          'Tyrone Wells',
          'Vanessa Carlton',
          'The Weepies',
          'Xavier Rudd',
          'Wakey!Wakey!',
          'The Civil Wars',
          'Josh Ritter',
          'Heather Janssen',
          'Playjerise',
          'Corey Gray',
          'Michelle Featherstone',
          'The Wailin Jennys',
          'Katy McAllister',
          'Benjamin Taylor',
          'Tyler Hilton',
          'Julia Sheer',
          'A Fine Frenzy',
          'Jamestown Story',
          'Chase Coy',
          'Patty Griffin',
          'Odessa',
          'Jamie Scott'
        ]
      },

      # rock
      {
        :genre => "rock",
        :artists => [
          'Talking Heads',
          'Carl Perkins',
          'Curtis Mayfield',
          'R.E.M.',
          'Lynyrd Skynyrd',
          'Nine Inch Nails',
          'Booker T. and the MGs',
          'Guns N Roses',
          'Tom Petty',
          'Carlos Santana',
          'The Yardbirds',
          'Black Sabbath',
          'Creedence Clearwater Revival',
          'Elvis Costello',
          'Elvis Presley',
          'The Stooges',
          'Eagles',
          'Radiohead',
          'Frank Zappa',
          'The Police',
          'Cream',
          'The Kinks',
          'Tina Turner',
          'Joni Mitchell',
          'Metallica',
          'The Sex Pistols',
          'Aerosmith',
          'Parliament',
          'Funkadelic',
          'Eric Clapton',
          'The Allman Brothers Band',
          'Queen',
          'Pink Floyd',
          'The Band',
          'Elton John',
          'Janis Joplin',
          'The Byrds',
          'Sly and the Family Stone',
          'Van Morrison',
          'The Doors',
          'Simon and Garfunkel',
          'David Bowie',
          'John Lennon',
          'Lenny Kravitz',
          'Neil Young',
          'The Who',
          'The Clash',
          'Prince',
          'The Ramones',
          'Jerry Lee Lewis',
          'Bruce Springsteen',
          'U2',
          'Bo Diddley',
          'The Velvet Underground',
          'Stevie Wonder',
          'Led Zeppelin',
          'The Beach Boys',
          'Bob Marley & the Wailers',
          'Little Richard',
          'James Brown',
          'Jimi Hendrix',
          'Skrillex',
          'The Rolling Stones',
          'Bob Dylan',
          'Meat Loaf',
          'Peter Frampton',
          'Nazareth',
          'Jefferson Airplane',
          'Twisted Sister',
          'Grand Funk Railroad',
          'Fleetwood Mac',
          'The Cult',
          'Foo Fighters',
          'Slayer',
          'Bon Jovi',
          'Steve Miller Band',
          'Journey',
          'Whitesnake',
          'Steppenwolf',
          'Janes Addiction',
          'Foreigner',
          'Stone Temple Pilots',
          'Pantera',
          'Ted Nugent',
          'Rage Against the Machine',
          'Alice in Chains',
          'Rush',
          'Motley Crue',
          'Def Leppard',
          'Judas Priest',
          'Kiss',
          'Sex Pistols',
          'Iron Maiden',
          'Soundgarden',
          'Van Halen',
          'Deep Purple',
          'Megadeth',
          'MC5',
          'Bad Company',
          'Cheap Trick',
        ]
      }
    ]

  end

end
